monitor all sub commands for non-zero exit status
git-svn-id: svn+ssh://src.dsl.bbn.com/svn/openmap/trunk@8 f68c23cc-7f87-4fbc-acfa-d9760b90acc1

diff --git a/autobuild b/autobuild
--- a/autobuild
+++ b/autobuild
@@ -18,8 +18,8 @@
 # 
 # $Source: /cvs/distapps/openmap/Attic/autobuild,v $
 # $RCSfile: autobuild,v $
-# $Revision: 1.2 $
-# $Date: 1998/04/20 22:18:55 $
+# $Revision: 1.3 $
+# $Date: 1998/04/21 13:16:29 $
 # $Author: tmitchel $
 # 
 # **********************************************************************
@@ -75,21 +75,34 @@ export DocPackages
 
 #echo $CLASSPATH
 
+# set: -e = exit if a command exits with a non-zero exit status
+# set: -v = Print shell input lines as they are read
+# set: -x = Print commands and their  arguments  as  they  are executed.
+set -evx
+
+#
+## Create a build directory
+#
 rm -rf $BuildDir
-
-if mkdir -p $BuildDir ; then
-  echo "Created build directory $BuildDir.";
-else
-  # mkdir failed
-  echo "Failed to create directory $BuildDir.  Exiting.";
-  exit 1
-fi
-
+mkdir -p $BuildDir
 cd $BuildDir
+
+#
+## Export the sources
+#
 cvs export -Dnow openmap
 cd openmap
+
+#
+## Build the software
+#
 gmake all
+
+#
+## Create the bean jar file
+#
 jar cvfm0 ../mapBean.jar com/bbn/openmap/Manifest.txt `find com -name *.class -print`
+
 
 #
 ## Add javadoc documentation
